spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/basicJpa
    username: sa
    password: qeqe12
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show-sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google :
            client-id: 758960019232-slgejmq7qiqbs8t03gkjl7cnaisa64f4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


logging:
  level:
    org.hibernate.SQL: debug

    # 쿼리 파라미터 로그 남기기
    org.hibernate.type: trace


