spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth2?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: geniusadmin!

  jpa:
    hibernate:
      # 애플리케이션 실행 시점에 테이블을 drop하고, 다시 생성
      ddl-auto: create

    properties:
      hibernate:
        # 옵션은 System.out에 하이버네이트 실행 sql을 남김
        # show_sql: true

        format_sql: true

  security:
    oauth2:
      client:
        registration:
          github :
            client-id: da5b2fb0aaa3713df827
            client-secret: 6d45f9eccc32d7c9a10e8e7d2f25bd7001fd73b9
            scope:
              - email
              - profile


          google:
            client-id: 1087770443158-75onsd4cnq4nn4qqdabdlgv8opai1bnd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
