spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth2?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: geniusadmin!

  jpa:
    hibernate:
      # 애플리케이션 실행 시점에 테이블을 drop하고, 다시 생성
      ddl-auto: create

    properties:
      hibernate:
        # 옵션은 System.out에 하이버네이트 실행 sql을 남김
        # show_sql: true

        format_sql: true

logging.level:
  # 옵션은 logger를 통해 하이버네이트 실행 sql을 남김
  org.hibernate.SQL: debug

  # org.hibernate.type: trace

#  security:
#    oauth2:
#      client:
#        registration:
#          google :
#            client-id: 758960019232-slgejmq7qiqbs8t03gkjl7cnaisa64f4.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile

